'use client';
import {useState} from 'react';
import {FAMILY_MEMBERS,type FamilyId} from './family';
import {DEFAULT_SEATS,dinnerError,dinnerMemory,dinnerTension,type DinnerChoice} from './family-dinner';
import type {LifeState} from './engine';
import type {RoomLayout} from '@/components/room-organizer/lib/types';
export function DinnerPanel({life,home,busy,onDinner}:{life:LifeState;home:RoomLayout;busy:boolean;onDinner:(seats:FamilyId[],choice:DinnerChoice)=>void}):JSX.Element{
  const [seats,setSeats]=useState<FamilyId[]>([...DEFAULT_SEATS]);const error=dinnerError(life,home),memory=dinnerMemory(life);
  return <section className="family-pressure dinner-panel"><p className="life-eyebrow">FAMILY STORY EVENT</p><h3>Everyone at the table</h3><p>Arrange five seats clockwise. People next to each other affect each other’s trust and resentment.</p><div className="dinner-seats">{seats.map((id,index)=><label key={index}>Seat {index+1}<select aria-label={'Dinner seat '+(index+1)} value={id} onChange={e=>{const next=[...seats],other=next.indexOf(e.target.value as FamilyId);next[index]=next[other]!;next[other]=id;setSeats(next);}}>{FAMILY_MEMBERS.map(m=><option key={m.id} value={m.id}>{m.id==='self'?life.name+' (you)':m.name}</option>)}</select></label>)}</div><p><b>Table tension: {dinnerTension(life,seats)} / 100</b></p><small>Dana tends to favor Casey; Morgan tends to favor Riley. Seating a parent beside their favorite adds tension.</small>{memory&&<blockquote>Still on your mind: {memory.slice(0,180)}{memory.length>180?'…':''}</blockquote>}<button disabled={busy||!!error} onClick={()=>onDinner(seats,'include')}>Give everyone a turn · $20</button><button disabled={busy||!!error} onClick={()=>onDinner(seats,'sides')}>Back the favorites · $20</button><small>{error??'One dinner per day · Advances one hour. Tension of 37+ can overwhelm mediation; backing favorites raises it.'}</small>{life.memories.find(m=>m.topic==='family-dinner')&&<p className="dinner-result">{life.memories.find(m=>m.topic==='family-dinner')!.text}</p>}</section>;
}
