'use client';
import { FAMILY_MEMBERS,familyPresent } from './family';
import { familyPressure } from './family-events';
import type { LifeState } from './engine';

export function FamilyPanel({life,busy,onGender,onTalk,onChoice,onFight}:{life:LifeState;busy:boolean;onGender:(gender:'boy'|'girl'|null)=>void;onTalk:(id:string)=>void;onChoice:(choice:'support'|'comply')=>void;onFight?:(name:string)=>void}):JSX.Element{
  const pressure=familyPressure(life);
  return <section className="family-panel"><p className="life-eyebrow">YOUR FAMILY</p><h2>Stuck in the middle</h2><p>Casey is older. Riley is younger. You are the middle child.</p><label>Your character<select value={life.gender??''} onChange={e=>onGender(e.target.value as 'boy'|'girl'||null)}><option value="">Choose boy or girl</option><option value="boy">Boy</option><option value="girl">Girl</option></select></label><small>Family expectations change with this choice. Your abilities and interests are yours to choose.</small><div className="family-order"><span>Casey<small>Oldest</small></span><strong>{life.name}<small>Middle child</small></strong><span>Riley<small>Youngest</small></span></div>{FAMILY_MEMBERS.filter(m=>m.id!=='self').map(member=>{const bond=life.family.bonds[member.id].self!,present=familyPresent(member.id,life.stage);return <article className="life-person-row" key={member.id}><strong>{member.name} · {member.label}</strong><small>{present?`Toward you: affection ${bond.affection} · trust ${bond.trust} · resentment ${bond.resentment}`:'Joins the household in childhood.'}</small><small>You toward them: trust {life.family.bonds.self[member.id]!.trust} · resentment {life.family.bonds.self[member.id]!.resentment}</small><button disabled={busy||!present||life.completed||life.health<=0} onClick={()=>onTalk('family:'+member.id)}>Spend time with {member.name}</button>{onFight&&<button disabled={busy||!present||life.completed||life.health<=0} title="Starting a fight is a fight you lose." onClick={()=>onFight(member.name)}>Throw hands</button>}</article>;})}{pressure&&<article className="family-pressure"><h3>What they expect of you</h3><p>{pressure}</p><button disabled={busy||life.completed||life.health<=0} onClick={()=>onChoice('support')}>Name what I need. Ask for support.</button><button disabled={busy||life.completed||life.health<=0} onClick={()=>onChoice('comply')}>Keep the peace. Carry it myself.</button><small>These are this family’s expectations, not rules about boys or girls.</small></article>}{life.family.resolvedStages.includes(life.stage)&&<p>Your response is saved in Memories. Its relationship effects remain.</p>}</section>;
}
