import {describe,expect,it} from 'vitest';
import {dateError,finishActivity,newLife,parseLife} from './engine';
import {FAMILY_MEMBERS,newFamily} from './family';
import {familyPressure,resolveFamilyPressure} from './family-events';
describe('middle-child household',()=>{
  it('has two parents and two siblings with the player in the middle',()=>{const f=newFamily();expect(FAMILY_MEMBERS.filter(m=>m.role==='parent')).toHaveLength(2);expect(FAMILY_MEMBERS.filter(m=>m.role==='sibling')).toHaveLength(2);expect(f.birthOrder).toEqual(['older','self','younger']);expect(f.bonds.older.younger).toBeDefined();expect(f.bonds.younger.older).not.toBe(f.bonds.older.younger);});
  it('migrates old saves without changing their life or guessing gender',()=>{const s=newLife('Taylor');const {family,gender,...old}=s;expect(family).toBeDefined();expect(gender).toBeNull();const parsed=parseLife(old)!;expect(parsed.name).toBe('Taylor');expect(parsed.money).toBe(s.money);expect(parsed.family.birthOrder[1]).toBe('self');expect(parsed.gender).toBeNull();expect(parseLife({...s,family:{}})).toBeNull();});
  it('spending time changes family bonds without adding relatives to dating',()=>{const s={...newLife(),stage:3};const next=finishActivity(s,'talk','family:older');expect(next.family.bonds.older.self!.affection).toBeGreaterThan(s.family.bonds.older.self!.affection);expect(next.relationships).toEqual(s.relationships);expect(next.family.bonds['parent-a'].younger).toEqual(s.family.bonds['parent-a'].younger);expect(dateError(next,'family:older')).not.toBeNull();});
  it('uses different expectations with lasting choices, once per chapter',()=>{const boy={...newLife(),stage:2,gender:'boy' as const},girl={...boy,gender:'girl' as const};expect(familyPressure(boy)).not.toBe(familyPressure(girl));const result=resolveFamilyPressure(boy,'comply');expect(result.family.bonds.self['parent-b']!.resentment).toBe(10);expect(result.family.bonds['parent-b'].self!.affection).toBeGreaterThan(boy.family.bonds['parent-b'].self!.affection);expect(resolveFamilyPressure(result,'support')).toBe(result);expect(familyPressure({...result,gender:'girl'})).toBeNull();expect(parseLife(JSON.parse(JSON.stringify(result)))?.family).toEqual(result.family);});
  it('introduces the youngest in childhood and preserves a support response',()=>{const baby=newLife();expect(finishActivity(baby,'talk','family:younger')).toBe(baby);const child={...baby,stage:1,gender:'girl' as const};const result=resolveFamilyPressure(child,'support');expect(result.family.bonds.younger.self!.trust).toBeGreaterThan(child.family.bonds.younger.self!.trust);expect(result.memories[0]!.topic).toBe('family');});
});
