'use client';
import { Download, Play, Square, Upload, Volume2, VolumeX, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { storedSample } from './sample-store';
import { downloadJson } from './save-system';
import { defaultPattern, parsePattern, voice, wav } from './studio-engine';

export function MusicDesk({onClose}:{onClose:()=>void}):JSX.Element {
  const [song,setSong]=useState(defaultPattern),[loaded,setLoaded]=useState(false),[playing,setPlaying]=useState(false),[step,setStep]=useState(-1),[sampleName,setSampleName]=useState('Load a sample'),[message,setMessage]=useState('Your beat saves automatically.'),[exporting,setExporting]=useState(false);
  const ac=useRef<AudioContext|null>(null),sample=useRef<AudioBuffer|null>(null),current=useRef(song),notes=useRef(new Set<AudioScheduledSourceNode>()),timers=useRef<ReturnType<typeof setTimeout>[]>([]);current.current=song;
  function context(){return ac.current??(ac.current=new AudioContext());}
  function stop(){setPlaying(false);setStep(-1);for(const node of notes.current){try{node.stop();}catch{/* already finished */}}notes.current.clear();timers.current.forEach(clearTimeout);timers.current=[];}
  useEffect(()=>{let active=true;try{const p=parsePattern(JSON.parse(localStorage.getItem('yourspace-studio-pattern')??'null'));if(p)setSong(p);}catch{setMessage('Could not load the previous beat. Import a pattern backup to recover it.');}setLoaded(true);void storedSample().then(async file=>{if(file&&active){const buffer=await context().decodeAudioData(await file.arrayBuffer());if(active){sample.current=buffer;setSampleName(file.name);}}}).catch(()=>{if(active)setMessage('Patterns save here; sample storage is unavailable in this browser.');});return()=>{active=false;};},[]);
  useEffect(()=>{if(!loaded)return;try{localStorage.setItem('yourspace-studio-pattern',JSON.stringify(song));}catch{setMessage('Beat could not save. Export a pattern backup before closing.');}},[song,loaded]);
  useEffect(()=>{if(!playing)return;const c=context();let next=c.currentTime+.06,index=0;const timer=setInterval(()=>{while(next<c.currentTime+.1){const p=current.current,n=index;for(let row=0;row<4;row++)if(p.pattern[row]![n]&&!p.muted[row]){const source=voice(c,c.destination,row,next,p.volumes[row]!,sample.current);if(source){notes.current.add(source);source.addEventListener('ended',()=>notes.current.delete(source),{once:true});}}timers.current.push(setTimeout(()=>setStep(n),Math.max(0,(next-c.currentTime)*1000)));if(timers.current.length>32)timers.current.splice(0,16);next+=60/p.bpm/4;index=(index+1)%16;}},25);return()=>{clearInterval(timer);timers.current.forEach(clearTimeout);timers.current=[];};},[playing]);
  useEffect(()=>{const hidden=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',hidden);return()=>{document.removeEventListener('visibilitychange',hidden);timers.current.forEach(clearTimeout);void ac.current?.close();};},[]);
  async function exportAudio(){setExporting(true);try{const p=current.current,length=16*60/p.bpm/4;const c=new OfflineAudioContext(1,Math.ceil((length*2+4)*44100),44100);for(let bar=0;bar<2;bar++)for(let s=0;s<16;s++)for(let r=0;r<4;r++)if(p.pattern[r]![s]&&!p.muted[r])voice(c,c.destination,r,bar*length+s*60/p.bpm/4,p.volumes[r]!,sample.current);const rendered=await c.startRendering();const url=URL.createObjectURL(new Blob([wav(rendered)],{type:'audio/wav'}));const a=document.createElement('a');a.href=url;a.download='bedroom-studio-beat.wav';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Two bars exported as WAV, with room for the final sound to fade.');}catch(e){setMessage('Could not export audio: '+String(e));}finally{setExporting(false);}}
  return <div className="life-modal-backdrop life-on-top"><section className="life-settings life-music" role="dialog" aria-modal="true" aria-label="Music studio"><header><div><p className="life-eyebrow">MAKE A LITTLE NOISE</p><h2>Bedroom studio</h2></div><button aria-label="Close studio" onClick={onClose}><X/></button></header><p>Four voices. Sixteen steps. Something only you would make.</p><div className="life-music-controls"><button className="studio-play" aria-label={playing?'Stop beat':'Play beat'} onClick={async()=>{try{if(playing)stop();else{await context().resume();setPlaying(true);}}catch{setMessage('Audio could not start. Tap a pad to try again.');}}}>{playing?<Square size={18}/>:<Play size={18}/>} {playing?'Stop':'Play'}</button><label>Tempo<input aria-label="Tempo" type="number" min={50} max={200} value={song.bpm} onChange={e=>setSong(p=>({...p,bpm:Math.max(50,Math.min(200,Number(e.target.value)||110))}))}/><small>BPM</small></label><span className="studio-beat">{playing?`${Math.floor(step/4)+1} . ${step%4+1}`:'4 / 4'}</span></div>
  <div className="life-sequencer"><div className="step-numbers"><span>VOICE</span>{Array.from({length:16},(_,s)=><span key={s}>{s+1}</span>)}</div>{['Kick','Snare','Hi-hat','Sample'].map((name,r)=><div key={name}><button className="voice-pad" onClick={async()=>{try{await context().resume();if(r===3&&!sample.current){setMessage('Load an audio file for the sample pad.');return;}voice(context(),context().destination,r,context().currentTime,song.volumes[r]!,sample.current);}catch{setMessage('This browser could not play audio.');}}}>{name}</button>{song.pattern[r]!.map((on,s)=><button key={s} aria-label={`${name} step ${s+1}`} aria-pressed={on} className={(on?'on ':'')+(playing&&step===s?'playing ':'')+(s%4===0?'beat-start':'')} onClick={()=>setSong(p=>({...p,pattern:p.pattern.map((row,i)=>i===r?row.map((v,j)=>j===s?!v:v):row)}))}/>)}</div>)}</div>
  <div className="studio-mixer">{['Kick','Snare','Hi-hat','Sample'].map((name,r)=><label key={name}><span>{name}<button aria-label={`${song.muted[r]?'Unmute':'Mute'} ${name}`} aria-pressed={song.muted[r]} onClick={()=>setSong(p=>({...p,muted:p.muted.map((v,i)=>i===r?!v:v)}))}>{song.muted[r]?<VolumeX size={15}/>:<Volume2 size={15}/>}</button></span><input aria-label={`${name} volume`} type="range" min={0} max={1} step={.05} value={song.volumes[r]} onChange={e=>setSong(p=>({...p,volumes:p.volumes.map((v,i)=>i===r?Number(e.target.value):v)}))}/></label>)}</div>
  <label className="studio-sample file-button"><Upload size={18}/><span><strong>{sampleName}</strong><small>WAV, MP3 or another supported audio file · up to 20 MB · first 4 seconds play</small></span><input type="file" accept="audio/*" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>20*1024*1024)throw new Error('Choose a sample under 20 MB.');const decoded=await context().decodeAudioData(await file.arrayBuffer());sample.current=decoded;setSampleName(file.name);await storedSample(file);setMessage('Sample loaded and saved for next time.');}catch(err){setMessage('Sample: '+(err instanceof Error?err.message:String(err)));}}}/></label>
  <div className="studio-export"><button disabled={exporting} onClick={()=>void exportAudio()}><Download size={16}/>{exporting?'Rendering…':'Export WAV'}</button><button onClick={()=>downloadJson(song,'bedroom-studio-pattern.json')}>Save pattern file</button><label className="file-button">Load pattern<input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>100000)throw new Error('Pattern file is too large.');const parsed=parsePattern(JSON.parse(await file.text()));if(!parsed)throw new Error('Invalid pattern file.');stop();setSong(parsed);setMessage('Pattern loaded. Your sample stays on its pad.');}catch(err){setMessage(String(err));}}}/></label><button onClick={()=>{if(window.confirm('Clear all steps? Your sample and volumes will stay.')){stop();setSong(p=>({...p,pattern:p.pattern.map(r=>r.map(()=>false))}));}}}>Clear steps</button></div><p className="panel-feedback" role="status">{message}</p></section></div>;
}
