'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { parseStoredLayout } from '@/components/room-organizer/lib/schema';
import { starterHome } from './home';
import { beginDesign, editBlueprint, emptyProperties, loadProperties, placeBlueprint, renameBlueprint, saveBlueprint, saveProperties, type Blueprint, type Properties } from './properties';
import type { RoomLayout } from '@/components/room-organizer/lib/types';

export function PropertyPanel({home,onMove,onError}:{home:RoomLayout;onMove:(h:RoomLayout)=>void;onError:(s:string)=>void}):JSX.Element {
  const [p,setP]=useState<Properties>(emptyProperties()),[chosen,setChosen]=useState(''),[ready,setReady]=useState(false);
  const [title,setTitle]=useState(''),[removed,setRemoved]=useState<Blueprint|null>(null);
  useEffect(()=>{try{setP(loadProperties());setReady(true);}catch(e){onError(String(e));}},[onError]);
  function update(next:Properties):boolean{try{saveProperties(next);setP(next);return true;}catch(e){onError('Could not save designs: '+String(e));return false;}}
  return <section className="property-panel"><h3>Your houses</h3><p>Save a design, place a copy on a lot, then move in. Your previous home is saved as a blueprint before moving.</p><div className="property-actions"><button disabled={!ready} onClick={()=>{try{if(update(saveBlueprint(p,home,home.name)))onError('Current home saved as a blueprint.');}catch(e){onError(String(e));}}}>Save current home</button><Link href="/design" onClick={e=>{try{beginDesign();}catch(err){e.preventDefault();onError(String(err));}}}>Open design studio →</Link><label className="property-import">Import house JSON<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>5e6)throw new Error('Use a file smaller than 5 MB.');const raw=JSON.parse(await f.text());const layout=parseStoredLayout(raw.layout??raw.home??raw);if(!layout)throw new Error('Invalid house file.');update(saveBlueprint(p,layout,layout.name));}catch(err){onError(String(err));}}}/></label></div>
    <button disabled={!ready} onClick={()=>{if(!window.confirm('Move into the updated starter home? Your current home will be saved as a blueprint.'))return;try{const next=saveBlueprint(p,home,home.name);saveProperties(next);setP(next);onMove(starterHome());}catch(e){onError(String(e));}}}>Move into updated starter home</button>
    <label>Blueprint to place<select value={chosen} onChange={e=>{setChosen(e.target.value);setTitle(p.blueprints.find(b=>b.id===e.target.value)?.name??'');}}><option value="">Choose a saved house</option>{p.blueprints.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
    {chosen&&<div className="blueprint-manager"><label>House name<input maxLength={80} value={title} onChange={e=>setTitle(e.target.value)}/></label><button disabled={!title.trim()} onClick={()=>{try{if(update(renameBlueprint(p,chosen,title)))onError('Blueprint renamed. Placed houses keep their names.');}catch(e){onError(String(e));}}}>Rename</button><Link href="/design" onClick={e=>{if(!window.confirm('Open a copy in the studio? Your current draft will be backed up and the saved blueprint stays on your shelf.')){e.preventDefault();return;}try{editBlueprint(chosen);}catch(error){e.preventDefault();onError(String(error));}}}>Edit a copy in studio →</Link><button onClick={()=>{const b=p.blueprints.find(b=>b.id===chosen);if(!b||!window.confirm('Remove this blueprint from the shelf? Placed copies stay. You can undo here until you leave this screen.'))return;if(update({...p,blueprints:p.blueprints.filter(b=>b.id!==chosen)})){setRemoved(b);setChosen('');onError('Blueprint removed. Undo is available on this screen.');}}}>Remove from shelf</button></div>}
    {removed&&<button disabled={p.blueprints.length>=100} onClick={()=>{if(update({...p,blueprints:[removed,...p.blueprints]})){setChosen(removed.id);setTitle(removed.name);setRemoved(null);}}}>Undo removal of {removed.name}</button>}
    {chosen&&<button onClick={()=>{const b=p.blueprints.find(x=>x.id===chosen);if(!b)return;const url=URL.createObjectURL(new Blob([JSON.stringify(b.layout,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='house-blueprint.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export selected blueprint</button>}
    <div className="property-lots">{p.lots.map((lot,i)=><article key={i}><span>LOT {i+1}</span><strong>{lot?.name??'Empty plot'}</strong>{lot?<svg viewBox={`0 0 ${lot.layout.width} ${lot.layout.height}`} role="img" aria-label={`${lot.name} floor plan`}><rect width={lot.layout.width} height={lot.layout.height} fill={lot.layout.floors[0]?.floorColor??'#bfae8e'}/>{lot.layout.floors[0]?.items.filter(x=>x.position).map(x=><rect key={x.id} x={x.position!.x+lot.layout.width/2-x.width/2} y={x.position!.z+lot.layout.height/2-x.depth/2} width={x.width} height={x.depth} fill={x.color} transform={`rotate(${(x.rotation??0)*180/Math.PI} ${x.position!.x+lot.layout.width/2} ${x.position!.z+lot.layout.height/2})`}/>)}</svg>:<div className="empty-plot">A place for your next idea</div>}<button disabled={!chosen||!ready} onClick={()=>{if(lot&&!window.confirm('Replace this lot? Its original blueprint remains on your shelf.'))return;update(placeBlueprint(p,chosen,i));}}>{lot?'Replace with design':'Place design'}</button>{lot&&<button onClick={()=>{try{const next=saveBlueprint(p,home,home.name);saveProperties(next);setP(next);onMove(structuredClone(lot.layout));}catch(e){onError(String(e));}}}>Move into this house</button>}</article>)}</div><small>{p.blueprints.length} saved blueprints · Placed copies stay unchanged when you edit a design.</small></section>;
}
