'use client';
import { X, Download, Upload, Shield, Keyboard, Sparkles } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import { websiteUrl } from './bridge';
import type { LifeState } from './engine';
interface Props { life:LifeState; site:string; danger:boolean; onClose:()=>void; onSave:(name:string,site:string,danger:boolean)=>void; onExport:()=>void; onImport:(file:File)=>Promise<void>; onRestore:()=>void; onNew:(adult:boolean)=>void; feedback:string }
export function SettingsPanel(p:Props):JSX.Element {
  const [name,setName]=useState(p.life.name),[site,setSite]=useState(p.site),[danger,setDanger]=useState(p.danger),[error,setError]=useState('');
  return <div className="life-modal-backdrop"><section className="life-settings settings-panel" role="dialog" aria-modal="true" aria-label="Creator settings"><header><div><p className="life-eyebrow">YOUR WORLD, YOUR RULES</p><h2>Make it yours</h2><Link href="/scene">Review the 3D scene →</Link></div><button aria-label="Close settings" onClick={p.onClose}><X/></button></header>
    <div className="settings-group"><label>Character name<input maxLength={40} value={name} onChange={e=>setName(e.target.value)} autoComplete="off"/></label><label>Your website address<input type="url" value={site} onChange={e=>setSite(e.target.value)} spellCheck={false}/></label><p>The included demo unlocks your Founder room. Connect your own website using the bridge script in the code package.</p><label className="settings-toggle"><span><Shield size={18}/> Survival encounters<small>Prowlers begin in adolescence. Switch off for a peaceful life.</small></span><input type="checkbox" checked={danger} onChange={e=>setDanger(e.target.checked)}/></label><button className="life-primary" onClick={()=>{if(!name.trim()){setError('Give your character a name.');return;}if(!websiteUrl(site,location.href)){setError('Use an HTTPS address, or the included /website-demo.html.');return;}setError('');p.onSave(name.trim(),site,danger);}}>Save preferences</button></div>
    <div className="settings-group"><h3>Your progress</h3><p>Download a backup to keep your life, home, and blueprint shelf together.</p><div className="settings-grid"><button onClick={p.onExport}><Download size={16}/> Download backup</button><label className="file-button"><Upload size={16}/> Import backup<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(file){try{await p.onImport(file);}catch(err){setError(err instanceof Error?err.message:String(err));}}}}/></label><button onClick={p.onRestore}>Restore safe checkpoint</button></div></div>
    <details className="settings-group"><summary><Keyboard size={16}/> Controls & tips</summary><p>WASD to walk; Shift to run. On touch screens, hold an arrow and toggle Run. Drag the room to orbit and pinch to zoom. Tap an object for actions. Escape closes the current window; Space pauses life when a control is not focused.</p><p>Rest restores energy and health. Save a checkpoint at full health. Alarms become available again on the next game day. Your life pauses when you leave the browser tab.</p></details>
    <details className="settings-group"><summary><Sparkles size={16}/> Begin another story</summary><p>Your current household is backed up before a new character begins. Your saved designs stay on the shelf.</p><div className="settings-grid"><button onClick={()=>p.onNew(false)}>New seven-chapter life</button><button onClick={()=>p.onNew(true)}>New adult sandbox</button></div></details>
    <details className="settings-group"><summary>Credits & game scope</summary><p>Built on Bassem Chagra’s MIT house builder, with Apache-2.0 Generative Agents memory scoring and the modified GPL-3.0-or-later Micropolis engine. Full notices and source are included. City gameplay is called City Planning.</p><p>Single-player, browser-local saves and cosmetic website rewards. You can live on the ground floor; the editor also supports other floors. Town lots are separate homes. No cloud accounts or server-verified rewards.</p></details><p role="status" className={error?'panel-feedback error':'panel-feedback'}>{error||p.feedback}</p>
  </section></div>;
}
