'use client';
import {conflictChoiceError} from './core-conflicts';
import {FAMILY_MEMBERS} from './family';
import {downloadJson} from './save-system';
import {episodeEnding,PERSONAS,storySnapshot} from './story-director';
import {AGENT_IDS,type DirectedResponse,type StoryTone} from './story-director-state';
import {FAMILY_EPISODES} from './story-episodes';
import type {LifeState} from './engine';

export function StoryDirectorPanel({life,busy,onMode,onChoice,onWait,onError}:{life:LifeState;busy:boolean;onMode:(enabled:boolean,tone:StoryTone)=>void;onChoice:(id:string,response:DirectedResponse)=>void;onWait:()=>void;onError:(message:string)=>void}):JSX.Element{
  const d=life.director,scene=d.active,episode=FAMILY_EPISODES[life.stage],choices=d.chapters[life.stage]!,ended=life.completed||life.health<=0;
  const disabled=busy||ended;
  const names=(id:string)=>FAMILY_MEMBERS.find(m=>m.id===id)?.name??id;
  const responses:{id:DirectedResponse;label:string}[]=scene?.card?scene.card.choices.map((c,i)=>({id:i===0?'answer-a':'answer-b',label:c.answer})):episode?(['repair','escalate','avoid'] as const).map(id=>({id,label:episode.choices[id]})):[];
  return <section className="story-director"><p className="life-eyebrow">FAMILY STORY MODE</p><h2>{scene?.card?.title??episode?.title??'A family before words'}</h2><p>{scene?.card?.question??episode?.premise??'The family’s directed episodes begin in childhood. Your infancy memories remain below.'}</p><div className="director-controls"><button disabled={disabled} aria-pressed={d.enabled} onClick={()=>onMode(!d.enabled,d.tone)}>{d.enabled?'Pause story mode':'Start story mode'}</button><label>Story tone<select disabled={disabled} value={d.tone} onChange={e=>onMode(d.enabled,e.target.value as StoryTone)}><option value="grounded">Grounded</option><option value="tender">Tender</option><option value="chaotic">Chaotic</option></select></label></div><small>The tone changes who initiates the next scene. Your choices determine its consequences.</small>
    {episode&&!scene?.card&&<ol className="director-beats">{episode.beats.map((beat,i)=><li key={beat} aria-current={scene?.step===i?'step':undefined}>{i<choices.length?'✓':i+1} · {beat}</li>)}</ol>}
    {scene&&<article><p className="life-eyebrow">{scene.card?'PLAYER-WRITTEN SCENE':`SCENE ${scene.step+1} OF 3`} · {scene.kind==='argument'?'TENSION':'CONNECTION'}</p><h3>{scene.card?.title??episode!.beats[scene.step]}</h3><p className="life-objective">{scene.goal}</p><div className="director-dialogue">{scene.lines.map((line,i)=><blockquote key={i}><b>{names(line.speaker)}</b><p>{line.text}</p></blockquote>)}</div>{scene.recalled&&<details><summary>What brought this back</summary><p>{scene.recalled}</p></details>}<div className="life-choices">{responses.map(response=><button key={response.id} disabled={disabled||!d.enabled||!!conflictChoiceError(life,scene.card,response.id==='answer-a'?0:1)} title={conflictChoiceError(life,scene.card,response.id==='answer-a'?0:1)??undefined} onClick={()=>onChoice(scene.id,response.id)}>{response.label}</button>)}</div>{scene.card&&scene.card.choices.map((_,i)=>conflictChoiceError(life,scene.card,i)&&<p key={i}>{conflictChoiceError(life,scene.card,i)}</p>)}<small>15 game minutes · Relationships and later scenes remember your response.</small>{!d.enabled&&<p>Resume story mode to respond.</p>}</article>}
    {!scene&&d.enabled&&(d.queuedCard||episode&&choices.length<3)&&(life.family.moment?<p>Finish the current household moment in People, then this episode can begin.</p>:<>{d.queuedCard&&<p><b>Your choice leads to:</b> {d.cards.find(c=>c.id===d.queuedCard)?.title}</p>}<p>The next scene becomes available in {Math.max(0,Math.ceil(d.nextAt-life.minute))} game minutes. Daily activities move the story forward too.</p><button disabled={disabled} onClick={onWait}>Wait for the next scene</button></>)}
    {episode&&choices.length===3&&<p className="director-ending"><b>Episode complete</b><br/>{episode.endings[episodeEnding(choices)]}</p>}
    {d.lastOutcome&&<details open><summary>Your last consequence</summary><p>{d.lastOutcome}</p></details>}
    {Object.values(d.conflicts.decisions).some(v=>v&&!v.resolved)&&<p className="life-note">An earlier decision still has an aftermath coming. Daily activities advance the clock.</p>}<details><summary>What your family wants</summary>{AGENT_IDS.map(id=><article className="director-mind" key={id}><b>{names(id)}</b><p>{PERSONAS[id].want}</p><small>Afraid of: {PERSONAS[id].fear.toLowerCase()}</small>{d.agents[id].reflection&&<p><em>{d.agents[id].reflection}</em></p>}{d.agents[id].memories.slice(0,2).map((m,i)=><p key={i} className="life-note">{m.text}</p>)}</article>)}</details>
    <details><summary>About this story mode</summary><p>Local, rule-based characters with authored dialogue, personal memories and branching episodes. No AI service is connected.</p>{scene&&<p>{scene.reason}</p>}<button onClick={()=>{try{downloadJson(storySnapshot(life),'family-story-snapshot.json');}catch{onError('Could not export the story snapshot.');}}}>Export story snapshot</button></details>
  </section>;
}
