'use client';
import {useState} from 'react';
import {conflictStartError,conflictLibraryError} from './core-conflicts';
import {downloadJson} from './save-system';
import {blankStoryCard,parseStoryCard,exportStoryPack,storyLinkError,type StoryCard,type StoryImpact} from './story-cards';
import {storyEpisodeCatalog} from './story-samples';
import {readStoryImport,storyImportError} from './story-workshop';
import type {LifeState} from './engine';
export function StoryWorkshopPanel({life,onClose,onSave,onApprove,onImport,onPlay}:{life:LifeState;onClose:()=>void;onSave:(card:StoryCard)=>void;onApprove:(id:string,reviewer:string,choices:StoryCard['choices'])=>void;onImport:(data:unknown)=>void;onPlay:(id:string)=>void}):JSX.Element{
  const [draft,setDraft]=useState(()=>blankStoryCard(life.name,crypto.randomUUID())),[message,setMessage]=useState('');
  const [packFilter,setPackFilter]=useState('Core conflicts'),[catalogSearch,setCatalogSearch]=useState('');
  const catalog=storyEpisodeCatalog();
  const groupOf=(entry:typeof catalog[number])=>'group' in entry?String(entry.group):'Life stories';
  const shown=catalog.filter(entry=>(packFilter==='All packs'||groupOf(entry)===packFilter)&&entry.pack.cards[0]!.title.toLowerCase().includes(catalogSearch.toLowerCase()));
  const stored=life.director.cards.find(c=>c.id===draft.id),locked=!!stored;
  const canWork=life.job==='story-editor'&&life.stage>=3&&!life.completed&&life.health>0;
  const reviewCard=parseStoryCard({...draft,status:'approved'});
  const linkError=conflictLibraryError([...life.director.cards.filter(c=>c.id!==draft.id),draft])??storyLinkError([...life.director.cards.filter(c=>c.id!==draft.id),draft]);
  const approved=!!reviewCard&&!linkError;
  const change=(index:number,key:'answer'|'consequence'|'impact'|'nextId',value:string)=>setDraft(d=>({...d,choices:d.choices.map((c,i)=>i===index?{...c,[key]:key==='nextId'&&!value?undefined:value}:c) as StoryCard['choices']}));
  return <div className="life-modal-backdrop"><section className="life-computer story-workshop" role="dialog" aria-modal="true" aria-label="Story editor desk"><header><strong>Story editor desk</strong><button autoFocus onClick={onClose} aria-label="Close story editor">Close</button></header><div className="workshop-columns"><div><p className="life-eyebrow">QUESTION → ANSWERS → CONSEQUENCES</p><h2>What happens because of that choice?</h2><p>Write a dilemma with two answers. Explain both consequences yourself, or hand the saved draft to another person. Approved scenes expand Story mode.</p><p className="life-note">{canWork?'One approved assignment earns $120, advances one hour, and builds creativity.':'Apply for the Story editor job at the computer to create and approve assignments.'}</p>
    <label>Title<input maxLength={100} disabled={locked} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Written by<input maxLength={40} disabled={locked} value={draft.author} onChange={e=>setDraft({...draft,author:e.target.value})}/></label><label>The question<textarea maxLength={500} disabled={locked} value={draft.question} onChange={e=>setDraft({...draft,question:e.target.value})}/></label>
    <label>Earliest life stage<select disabled={locked} value={draft.minStage??1} onChange={e=>setDraft({...draft,minStage:Number(e.target.value)})}><option value={1}>Childhood</option><option value={2}>Teen years</option><option value={3}>Young adulthood</option><option value={4}>Adulthood</option><option value={5}>Later adulthood</option><option value={6}>Elder years</option></select></label><label>Who explains the consequences?<select disabled={locked} value={draft.reviewMode} onChange={e=>setDraft({...draft,reviewMode:e.target.value as 'self'|'peer',reviewer:e.target.value==='self'?draft.author:''})}><option value="self">I review my answers</option><option value="peer">Someone else reviews them</option></select></label>
    {draft.choices.map((choice,i)=><fieldset key={i}><legend>Answer {i+1}</legend><label>The answer<textarea maxLength={180} disabled={locked} value={choice.answer} onChange={e=>change(i,'answer',e.target.value)}/></label><label>What is the repercussion?<textarea maxLength={500} disabled={stored?.status==='approved'} value={choice.consequence} onChange={e=>change(i,'consequence',e.target.value)} placeholder="Who is affected? What changes immediately, and what might they remember?"/></label><label>Relationship effect<select disabled={stored?.status==='approved'} value={choice.impact} onChange={e=>change(i,'impact',e.target.value as StoryImpact)}><option value="repair">Rebuild trust · ease resentment</option><option value="escalate">Escalate conflict · lose trust</option><option value="avoid">Leave tension unresolved</option></select></label><label>Follow-up scene<select disabled={stored?.status==='approved'} value={choice.nextId??''} onChange={e=>change(i,'nextId',e.target.value)}><option value="">End this story here</option>{life.director.cards.filter(c=>c.status==='approved'&&c.id!==draft.id).map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label></fieldset>)}
    <label>Consequences reviewed by<input disabled={stored?.status==='approved'} maxLength={40} value={draft.reviewer} onChange={e=>setDraft({...draft,reviewer:e.target.value})}/></label><small>{draft.reviewMode==='peer'?'Use a different reviewer name. Names are credits, not verified accounts.':'You can write the answers and their repercussions yourself.'}</small><div className="director-controls"><button disabled={!canWork||locked||!parseStoryCard(draft)||!!linkError||life.director.cards.length>=512} onClick={()=>{onSave(draft);setMessage('Draft saved. Its question and answers are now locked for consequence review.');}}>Save answers for review</button><button disabled={!canWork||!stored||stored.status==='approved'||!approved||life.needs.energy<15} onClick={()=>{onApprove(draft.id,draft.reviewer,draft.choices);setMessage('Assignment approved. The story is in your library.');}}>Approve consequences · earn $120</button></div><small>Each consequence needs at least 10 characters. Approval checks completeness; you are responsible for whether the consequence makes sense.</small>{linkError&&<p role="alert">{linkError}</p>}<p role="status">{message}</p>
    </div><aside><h3>Your story library · {life.director.cards.length}/512</h3><button onClick={()=>{setDraft(blankStoryCard(life.name,crypto.randomUUID()));setMessage('New assignment.');}}>New assignment</button><details><summary>Add a playable episode</summary><p>Choose stories to add to your 512-scene library. Adult episodes unlock in adulthood. The 85 conflict scenarios also track family pressure and charge the stated loan or cancellation costs. Other episodes use narrative and relationship consequences.</p><label>Scenario pack<select value={packFilter} onChange={e=>setPackFilter(e.target.value)}>{['All packs','Core conflicts','Deep secrets','Petty grievances','Sibling rivalries','In-law boundaries','Money and business','Estrangement','Addiction and cover-ups','Medical proxies','Life stories'].map(group=><option key={group}>{group}</option>)}</select></label><label>Find a scenario<input value={catalogSearch} onChange={e=>setCatalogSearch(e.target.value)} placeholder="Search episode titles"/></label><p>{shown.length} episodes in this view</p>{shown.map(entry=><article key={entry.key}><b>{entry.pack.cards[0]!.title}</b><p>{entry.description}</p><button disabled={life.stage<entry.minStage||!!storyImportError(life,entry.pack)} onClick={()=>{const error=storyImportError(life,entry.pack);if(error){setMessage(error);return;}onImport(entry.pack);setDraft(entry.pack.cards[0]!);setMessage('Episode added. Play its opening scene in Story mode. Built-in episodes do not earn wages.');}}>{life.stage<entry.minStage?'Available later in life':life.director.cards.some(c=>c.id===entry.pack.rootId)?'Added to library':'Add episode'}</button>{life.stage>=entry.minStage&&storyImportError(life,entry.pack)&&<small>{storyImportError(life,entry.pack)}</small>}</article>)}</details><label>Import a shared story<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>250000)throw new Error('Use a story file under 250 KB.');const data=JSON.parse(await file.text());const error=storyImportError(life,data);if(error)throw new Error(error);const cards=readStoryImport(data)!;onImport(data);setDraft(cards.find(c=>c.id===data.rootId)??cards[0]!);setMessage('Story imported with its linked scenes.');}catch(error){setMessage(String(error));}}}/></label><p className="life-note">Approve the ending scenes first, then select them as follow-ups while reviewing an earlier scene. Export episode includes every linked scene. Share exported JSON files or pass this device to another writer. This is a local library, not an online submission service.</p>
    {life.director.cards.map(card=><article className="director-mind" key={card.id}><b>{card.title}</b><p>{card.status==='approved'?`Reviewed by ${card.reviewer}`:`Awaiting consequences · ${card.author}`}</p><button onClick={()=>{setDraft(structuredClone(card));setMessage('');}}>Open {card.status==='draft'?'review':'story'}</button><button onClick={()=>{try{downloadJson(exportStoryPack(life.director.cards,card.id),'family-episode-'+card.id+'.json');}catch{setMessage('Could not export this story.');}}}>Export episode</button><details><summary>Preview answers and branches</summary>{card.choices.map((choice,i)=><div key={i}><p><b>{i+1}. {choice.answer}</b></p><p>{choice.consequence||'Awaiting a consequence review.'}</p><small>Effect: {choice.impact==='repair'?'rebuild trust':choice.impact==='escalate'?'increase conflict':'leave tension unresolved'} · Next: {choice.nextId?life.director.cards.find(c=>c.id===choice.nextId)?.title??'Missing scene':'End of this story'}</small></div>)}</details>{card.status==='approved'&&<button disabled={!!conflictStartError(life,card)||life.stage<(card.minStage??1)||life.completed||life.health<=0||!!life.family.moment||!!life.director.active||life.director.playedCards.includes(card.id)||!!life.director.queuedCard&&life.director.queuedCard!==card.id} onClick={()=>onPlay(card.id)}>{life.director.playedCards.includes(card.id)?'Played this life':conflictStartError(life,card)?'Play the opening first':life.stage<(card.minStage??1)?'Available later in life':'Play in story mode'}</button>}</article>)}{life.family.moment&&<p>Finish the open family scene before playing a library story.</p>}
    </aside></div></section></div>;
}
