import type {AgentId,StoryResponse} from './story-director-state';
export interface FamilyEpisode {title:string;premise:string;lead:AgentId;goal:string;beats:[string,string,string];choices:Record<StoryResponse,string>;endings:Record<'healing'|'rift'|'uneasy',string>}
/** Original household stories; no upstream Thistle Gulch dialogue or characters. */
export const FAMILY_EPISODES:Record<number,FamilyEpisode>={
  1:{title:'The promise nobody kept',premise:'A promised family afternoon disappears behind Casey’s achievement and Riley’s needs. Nobody remembers asking what the middle child wanted.',lead:'parent-a',goal:'Make room for the child who gets overlooked',beats:['The forgotten afternoon','Whose version counts?','A promise with a date'],choices:{repair:'Ask everyone to name what they need',escalate:'Demand they admit who matters most',avoid:'Say it is fine and make my own plans'},endings:{healing:'You put the next family afternoon on the calendar, with a turn for each child to choose.',rift:'Everyone remembers the accusation. Nobody agrees on what fairness looks like.',uneasy:'The house gets quiet. Your separate plans protect your time, but the promise stays unspoken.'}},
  2:{title:'Different rules under one roof',premise:'A request for independence exposes different rules for each sibling. The family calls it protection; you need them to hear what it costs.',lead:'parent-b',goal:'Negotiate independence without turning siblings into rivals',beats:['The rule that moved','Someone takes a side','A boundary that lasts'],choices:{repair:'Ask for one clear rule for all of us',escalate:'Point out every exception they made for Casey',avoid:'Keep my plans to myself'},endings:{healing:'The family agrees to explain its rules and revisit them, instead of changing them whenever someone complains.',rift:'The rules become a contest. Each sibling starts counting the other’s freedoms.',uneasy:'You gain privacy, but everyone fills the silence with their own suspicions.'}},
  3:{title:'Your paycheck, their expectations',premise:'Your first adult responsibilities become a household debate: helping out, proving yourself, and keeping a future of your own.',lead:'older',goal:'Separate mutual support from being treated as a resource',beats:['What the money means','The favor with strings','What you can actually give'],choices:{repair:'Offer help with a clear limit',escalate:'Tell them to stop treating me like a resource',avoid:'Avoid the question and focus on my own plans'},endings:{healing:'You agree on a specific contribution and protect time for your own future.',rift:'Help starts sounding like a debt, and every favor comes with a receipt.',uneasy:'Your money stays yours. The family still does not know what it can ask of you.'}},
  4:{title:'The invisible workload',premise:'Appointments, cleaning, remembering birthdays: the family relies on work that nobody counts until it stops happening.',lead:'younger',goal:'Make care visible and share it fairly',beats:['The thing nobody remembered','Who always catches it?','A fairer arrangement'],choices:{repair:'Write down the work and share it',escalate:'Refuse to fix anyone else’s mess',avoid:'Do my part quietly and avoid the fight'},endings:{healing:'The family names the hidden work and assigns it instead of assuming someone will catch it.',rift:'A missed task becomes proof in an old argument about who cares more.',uneasy:'The immediate problem is fixed. The uneven workload remains.'}},
  5:{title:'Who takes care of whom?',premise:'A parent needs more help. Old favoritism complicates a practical question: who has the time, and who gets to say no?',lead:'parent-a',goal:'Arrange care without sacrificing one person’s whole life',beats:['The call for help','An old pattern returns','A plan everyone can sustain'],choices:{repair:'Ask each person what they can realistically do',escalate:'Tell the favorite child it is finally their turn',avoid:'Offer a small favor without discussing the rest'},endings:{healing:'Care becomes a shared schedule with limits, instead of a test of loyalty.',rift:'The family turns care into repayment for old childhood debts.',uneasy:'Today is covered. Nobody has agreed what happens tomorrow.'}},
  6:{title:'What we leave unsaid',premise:'Sorting a box of family keepsakes becomes an argument about which memories deserve to survive.',lead:'older',goal:'Tell the truth without erasing the good',beats:['The box in the cupboard','Two versions of the same day','The story you leave behind'],choices:{repair:'Make room for the hurt and the happy memories',escalate:'Insist they admit what really happened',avoid:'Keep my own version and let them keep theirs'},endings:{healing:'The family keeps more than one account. Being heard matters more than winning the last word.',rift:'The keepsakes are divided along the same old lines. The argument becomes part of the inheritance.',uneasy:'Everyone takes a different memory home. Some things are preserved; others stay unresolved.'}},
};
