export type Skill = 'creativity' | 'learning' | 'kindness';
export interface Choice { label: string; consequence: string; skill: Skill; amount: number; cash?: number }
export interface StoryEvent { title: string; body: string; choices: Choice[] }
export interface LifeStage { name: string; age: string; theme: string; events: StoryEvent[] }
// Original narrative. No Alter Ego text or assets are included.
const choice = (label: string, consequence: string, skill: Skill, amount = 1, cash = 0): Choice => ({ label, consequence, skill, amount, cash });
export const STAGES: LifeStage[] = [
  { name: 'Infancy', age: '0–3', theme: 'A world becoming familiar', events: [
    { title: 'The first sound', body: 'Rain taps the window. Someone holds you close, humming a tune that almost matches it. You do not have words yet, but you have a choice of where to turn.', choices: [choice('Follow the rhythm', 'Music becomes one of your earliest comforts.', 'creativity'), choice('Reach for their hand', 'You learn that reaching out can bring someone closer.', 'kindness')] },
    { title: 'Beyond the blanket', body: 'A bright wooden block rolls just beyond your blanket. Your caregiver waits nearby, ready to help without taking over.', choices: [choice('Try to reach it yourself', 'Curiosity carries you a little farther.', 'learning'), choice('Make a game of calling them', 'You discover how much a shared laugh can do.', 'kindness')] },
    { title: 'The keepsake', body: 'Your family saves something from these first years. It will follow you from house to house, long after this room is forgotten.', choices: [choice('A scribbled picture', 'Your first picture becomes a family keepsake.', 'creativity'), choice('A bedtime storybook', 'A familiar story gives you a place to begin again.', 'learning')] },
    { title: 'Raised voices', body: 'Somewhere past the door, two grown voices climb over each other. You cannot understand the words, only the temperature of them. Your small body decides what to do before you do.', choices: [choice('Cry until someone comes', 'You learn, this early, that noise brings people — and that it works.', 'kindness'), choice('Go quiet and still', 'You learn, this early, how to make yourself small.', 'learning')] }
  ] },
  { name: 'Childhood', age: '4–12', theme: 'The first things you make your own', events: [
    { title: 'The empty lot', body: 'The children next door find an empty patch of land. They want a club, but nobody agrees what it should be.', choices: [choice('Design a clubhouse', 'Your drawings bring the group together.', 'creativity', 2), choice('Give everyone a role', 'You make room for the quietest child too.', 'kindness', 2)] },
    { title: 'A borrowed toy', body: 'You break a toy your friend lent you. For a moment it seems easier to say nothing.', choices: [choice('Tell them and help fix it', 'Honesty makes the friendship stronger.', 'kindness', 2), choice('Learn how it works first', 'You repair the toy and explain what happened.', 'learning', 2)] },
    { title: 'Show and tell', body: 'You can bring anything to school tomorrow. You want it to say something about you.', choices: [choice('Perform a little song', 'Making something for an audience feels exciting.', 'creativity', 2), choice('Explain your rock collection', 'You find that explaining a discovery is another kind of discovery.', 'learning', 2)] },
    { title: 'The good one and the easy one', body: 'Casey gets the praise for being first at everything. Riley gets the softness for being small. At dinner you realize there is no ready-made word for what you are — the one in the middle.', choices: [choice('Make them laugh across the table', 'You learn that being the funny one is a kind of place to stand.', 'creativity', 2), choice('Become the one who never causes trouble', 'You learn to earn a little peace by needing almost nothing.', 'learning', 2)] }
  ] },
  { name: 'Adolescence', age: '13–17', theme: 'Trying on possible futures', events: [
    { title: 'The school project', body: 'Your class is building a tiny virtual neighborhood. The team needs both a working program and somewhere worth visiting.', choices: [choice('Write the simulation', 'You discover the satisfaction of making a system work.', 'learning', 3), choice('Create the world and music', 'You develop a voice for places that do not exist yet.', 'creativity', 3)] },
    { title: 'A friend goes quiet', body: 'A friend stops coming to the usual meetup. Everyone assumes someone else has checked in.', choices: [choice('Go and listen', 'They remember that you showed up without demanding an explanation.', 'kindness', 3), choice('Make something to invite them back', 'A small creative gesture opens the conversation.', 'creativity', 2)] },
    { title: 'A first opportunity', body: 'The community center offers a weekend placement. It will not decide your whole future, but it might open a door.', choices: [choice('Help with the computers', 'You leave with practical experience and a reference.', 'learning', 2, 60), choice('Help run the art night', 'You learn to turn a creative idea into a real event.', 'creativity', 2, 60)] },
    { title: 'The referee', body: 'It happens again after school — a door slams, and the silence afterward is yours to fill. Somewhere along the way you became the one who keeps the whole house from tipping over.', choices: [choice('Step between them, again', 'You get good at reading a room before you even enter it.', 'kindness', 3), choice('Put your headphones on and leave', 'You learn that a door of your own can be its own kind of mercy.', 'creativity', 2)] }
  ] },
  { name: 'Young adulthood', age: '18–29', theme: 'A place, a paycheck, a direction', events: [
    { title: 'Your first keys', body: 'The house is finally yours to arrange. It is small, the bills are real, and the computer in the corner feels like a door to a larger world.', choices: [choice('Build a place to learn', 'You make room for the work you hope to do.', 'learning', 2), choice('Make it a place people gather', 'You decide your home should feel welcoming.', 'kindness', 2)] },
    { title: 'After the first shift', body: 'Your first real paycheck is not large. Still, you earned it. A coworker asks what you are saving for.', choices: [choice('A creative project', 'The money becomes a little more meaningful with a purpose.', 'creativity', 2), choice('A cushion for the unexpected', 'You begin thinking beyond the next payday.', 'learning', 2)] },
    { title: 'An unfamiliar address', body: 'Someone tells you about a website that connects people who build things. You write the address down instead of letting it disappear into the conversation.', choices: [choice('Look for collaborators', 'Your world begins reaching beyond the neighborhood.', 'kindness', 2), choice('Look for ideas to remix', 'You start seeing your own life as something you can change.', 'creativity', 2)] },
    { title: 'The call at a bad hour', body: 'The phone lights up after midnight. It is home, and it is the same argument in new clothes. You have your own life now, but the old role still has your number.', choices: [choice('Answer and talk them down', 'You keep the peace long distance — and notice, finally, how tired it makes you.', 'kindness', 2), choice('Let it ring and call back tomorrow', 'You practice, badly and then better, the word “later.”', 'learning', 2)] }
  ] },
  { name: 'Adulthood', age: '30–44', theme: 'What you choose to keep building', events: [
    { title: 'Room to grow', body: 'You have become good at keeping things running. Now you have to decide what deserves more of your attention.', choices: [choice('Take on a harder project', 'You make a deliberate investment in your craft.', 'learning', 3), choice('Protect time for people', 'Your relationships become something you actively maintain.', 'kindness', 3)] },
    { title: 'The neighborhood meeting', body: 'The old gathering space needs repairs. Some neighbors want to give up on it; others are waiting for someone to start.', choices: [choice('Organize a repair day', 'People who barely spoke begin working side by side.', 'kindness', 3), choice('Design a new use for the space', 'A fresh idea gives the project a second life.', 'creativity', 3)] },
    { title: 'A turning point at work', body: 'Your manager asks whether you want to keep mastering your role or help newer people find their footing.', choices: [choice('Deepen your specialty', 'You become someone others trust with the difficult work.', 'learning', 3), choice('Mentor someone new', 'You recognize a little of your younger self in them.', 'kindness', 3)] },
    { title: 'What you swore you would not repeat', body: 'You catch yourself using a voice you recognize — one that was once used on you. It stops you cold. The problems you were handed are yours now, to keep passing down or to break.', choices: [choice('Sit down and say sorry, plainly', 'You do the thing no one did for you, and it changes the whole room.', 'kindness', 3), choice('Write the pattern down to understand it', 'You turn an inheritance into something you can finally hold up to the light.', 'learning', 3)] }
  ] },
  { name: 'Middle age', age: '45–64', theme: 'Looking outward and looking back', events: [
    { title: 'The unfinished thing', body: 'You find an old project tucked away in a folder. It is less polished than you remember, and more alive than you expected.', choices: [choice('Finish it with what you know now', 'An old idea gains the patience it was missing.', 'creativity', 3), choice('Give it to someone starting out', 'The unfinished work becomes someone else’s beginning.', 'kindness', 3)] },
    { title: 'A changing street', body: 'The neighborhood does not look the same. New residents arrive, and familiar places change hands.', choices: [choice('Welcome the newcomers', 'Your memories become invitations instead of boundaries.', 'kindness', 3), choice('Document the street’s history', 'You find a new way to preserve a changing place.', 'learning', 3)] },
    { title: 'Time is a resource', body: 'You no longer believe you can do everything. Strangely, that makes some choices easier.', choices: [choice('Choose one meaningful project', 'Your attention becomes your most valuable contribution.', 'creativity', 3), choice('Make time to teach', 'What you learned starts living in other people.', 'learning', 3)] },
    { title: 'The parent, older now', body: 'A parent who once filled the whole house needs help crossing a parking lot. The old grievances do not vanish; they just have to share the car with this new, smaller person.', choices: [choice('Show up anyway, grudges and all', 'You learn that care and forgiveness are not the same thing — and you can offer one without the other.', 'kindness', 3), choice('Set the terms you can live with', 'You build a door that opens and closes, instead of a wall or a welcome mat.', 'learning', 3)] }
  ] },
  { name: 'Old age', age: '65+', theme: 'The life that remains in other lives', events: [
    { title: 'A familiar tune', body: 'Rain taps the window. A melody returns before you can remember where you first heard it.', choices: [choice('Record it for someone', 'A sound from the beginning finds a new listener.', 'creativity', 3), choice('Tell the story around it', 'You give the memory a voice.', 'kindness', 3)] },
    { title: 'The room you made', body: 'You look around at the objects you kept, the ones you replaced, and the empty spaces that now feel right.', choices: [choice('Pass along the useful things', 'Your belongings begin their next chapter.', 'kindness', 3), choice('Leave a guide to your work', 'Someone will be able to continue where you stopped.', 'learning', 3)] },
    { title: 'Your last page', body: 'A life cannot fit in a list of achievements. But a few things stand out: the choices you made, the people you helped, and the places you left different.', choices: [choice('Remember what you created', 'You leave a legacy of things that did not exist before you.', 'creativity', 3), choice('Remember who you reached', 'You leave a legacy in the lives that touched yours.', 'kindness', 3)] },
    { title: 'A younger version at the table', body: 'A child in the family has gone quiet in exactly the way you used to. They are standing in the middle of a room, keeping the peace, learning to need nothing. You recognize all of it.', choices: [choice('Tell them it was never their job', 'You hand down the sentence no one thought to hand you.', 'kindness', 3), choice('Make them something that says you saw it', 'You leave a small proof that being in the middle was witnessed.', 'creativity', 3)] }
  ] }
];
