import {coreConflictCatalog} from './core-conflicts';
import {exportStoryPack,type StoryCard} from './story-cards';

const credit={version:1 as const,author:'Family Simulator',reviewer:'Family Simulator',reviewMode:'self' as const,status:'approved' as const};
export const SAMPLE_EPISODE_ROOT='sample-broken-window-v1';
export function sampleStoryEpisode(){
  const cards:StoryCard[]=[
    {...credit,id:SAMPLE_EPISODE_ROOT,title:'The broken window',question:'Riley broke the kitchen window. Casey asks you, the middle child, to say it was already cracked. Riley waits for your answer. What do you do?',choices:[
      {answer:'Offer to stand beside Riley while they tell the truth.',consequence:'Riley feels less alone. Casey resents losing control of the plan, but the siblings have a chance to face the mistake together.',impact:'repair',nextId:'sample-window-truth-v1'},
      {answer:'Agree to the cover story so nobody gets in trouble tonight.',consequence:'Casey gets the agreement they wanted, but Riley now has to remember a lie. The siblings leave the real problem unresolved.',impact:'avoid',nextId:'sample-window-cover-v1'}]},
    {...credit,id:'sample-window-truth-v1',title:'Who pays for honesty?',question:'Riley admits what happened. Casey says you always make yourself look responsible while everyone else takes the blame. How do you respond?',choices:[
      {answer:'Admit that being the reasonable one can also be a way to take control.',consequence:'Casey feels heard instead of lectured. Riley proposes a shared repair plan, and the siblings begin rebuilding trust.',impact:'repair'},
      {answer:'Tell Casey that somebody in this family has to act like an adult.',consequence:'Casey hears an insult instead of an explanation. Riley goes quiet, and the argument becomes about who matters most in the family.',impact:'escalate'}]},
    {...credit,id:'sample-window-cover-v1',title:'Keeping the story straight',question:'The cover story starts falling apart. Casey wants Riley to repeat it, but Riley asks you whether telling the truth now would make everything worse. What do you say?',choices:[
      {answer:'We can admit we lied. I will take responsibility for my part.',consequence:'The siblings still have a broken window to explain, but Riley no longer carries the secret alone. Owning the lie creates a chance to repair trust.',impact:'repair'},
      {answer:'We already agreed. Riley needs to stop making this difficult.',consequence:'Riley feels trapped by both older siblings. Casey gets compliance, but pressure replaces trust and resentment grows.',impact:'escalate'}]}
  ];
  return exportStoryPack(cards,SAMPLE_EPISODE_ROOT);
}

type Answer=[string,string,StoryCard['choices'][0]['impact']];
function episode(key:string,title:string,question:string,opening:[Answer,Answer],paths:[{title:string;question:string;answers:[Answer,Answer]},{title:string;question:string;answers:[Answer,Answer]}]){
  const rootId=`episode-${key}-v1`;
  const choice=(a:Answer)=>({answer:a[0],consequence:a[1],impact:a[2]});
  const cards:StoryCard[]=[{...credit,id:rootId,title,question,choices:opening.map((a,i)=>({...choice(a),nextId:`${rootId}-${i}`})) as StoryCard['choices']},...paths.map((p,i)=>({...credit,id:`${rootId}-${i}`,title:p.title,question:p.question,choices:p.answers.map(choice) as StoryCard['choices']}))];
  return exportStoryPack(cards,rootId);
}
export function storyEpisodeCatalog(){return [
  ...coreConflictCatalog(),
  ...crisisEpisodes(),
  ...turningPointEpisodes(),
  {key:'window',minStage:1,description:'A broken window turns into a fight about responsibility.',pack:sampleStoryEpisode()},
  {key:'mystery',minStage:3,description:'A neighbor is dead. An accusation divides the family.',pack:episode('mystery','The house across the street','A neighbor has been found murdered. Casey claims to have seen someone leaving; Riley says Casey was too far away to be sure. What do you do?',[
    ['Help them record what they actually saw, including what they cannot be sure of.','The siblings agree to separate observation from suspicion. They still disagree, but neither has to pretend certainty.','repair'],
    ['Back Casey’s accusation in the neighborhood chat.','Riley feels ignored as a rumor spreads. The family becomes attached to a story before the evidence supports it.','escalate']
  ],[
    {title:'The missing minute',question:'A detective asks about the timeline. Riley admits they hid a message because they feared getting Casey in trouble. How do you respond?',answers:[['Encourage Riley to give the detective the message and explain the omission.','The message helps establish the timeline. The investigation remains with the detective, and the siblings stop treating honesty as betrayal.','repair'],['Blame Riley for making the family look suspicious.','Riley withdraws. The detective still needs the facts, while the siblings are left with a fresh grudge.','escalate']]},
    {title:'An accusation comes home',question:'Evidence clears the person Casey accused. Riley asks you to correct the public claim. Casey begs you not to embarrass them. What do you do?',answers:[['Correct the claim and admit your part in spreading it.','The family cannot undo the harm, but taking responsibility gives Riley a reason to trust you again.','repair'],['Quietly delete the message without correcting it.','The rumor survives elsewhere. Casey avoids an awkward apology, and Riley sees another family secret being protected.','avoid']]}
  ])},
  {key:'dating',minStage:3,description:'An adult dating show tests honesty, loyalty, and boundaries.',pack:episode('dating','Love, cameras, consequences','On an adult dating show, a producer asks you to hint that two contestants are dating in secret. Casey says it will make great television; Riley calls it cruel. What do you choose?',[
    ['Refuse the invented scandal and ask a contestant for a genuine conversation.','Riley appreciates the boundary. Casey worries you have wasted your moment, but the disagreement stays honest.','repair'],
    ['Repeat the rumor to secure more screen time.','The cameras turn toward you. Casey cheers, while Riley wonders whether family loyalty would survive the same treatment.','escalate']
  ],[
    {title:'After the final rose',question:'A contestant you like says they want to keep seeing you privately, without promising a relationship on camera. Your siblings disagree about what that means. What do you say?',answers:[['Respect the uncertainty and ask what pace feels comfortable for both of us.','You choose a conversation over a public promise. Riley feels heard, and Casey starts to question the need to turn everything into a competition.','repair'],['Tell everyone we are basically a couple already.','The contestant objects to a promise they never made. Your siblings argue about whether attention matters more than consent.','escalate']]},
    {title:'The reunion episode',question:'At the reunion, the contestant asks you to admit the rumor was invented. Casey wants you to blame editing. Riley wants you to take responsibility. What do you do?',answers:[['Apologize directly and correct the story.','The apology does not guarantee forgiveness or romance. It does show the family that being wrong need not mean doubling down.','repair'],['Blame the edit and refuse to discuss it.','The cameras move on, but Riley remembers how easily embarrassment became an excuse to avoid accountability.','avoid']]}
  ])},
  {key:'party',minStage:3,description:'A drug offer at an adult party leads to difficult choices.',pack:episode('party','One night out','At an adult party, someone offers you an unknown drug. Casey brushes off the risk; Riley wants to leave. What do you do?',[
    ['Decline and leave with Riley.','Riley feels supported. Casey is annoyed at first, but you leave room to talk without turning the decision into a contest.','repair'],
    ['Take it despite not knowing what it is.','The experience becomes frightening and unpredictable. Riley feels pressured to look after you, and Casey’s earlier confidence disappears.','escalate']
  ],[
    {title:'The morning group chat',question:'Casey jokes that you ruined the night. Riley asks you not to let the joke become another reason they feel unwelcome. What do you say?',answers:[['Explain the boundary without shaming anyone.','Casey hears that saying no was a personal decision, and Riley sees that their discomfort counts.','repair'],['Ignore the joke and let Riley handle it alone.','The argument stops in your chat, but Riley feels abandoned with the tension.','avoid']]},
    {title:'When the party stops',question:'Someone at the party collapses and is not responding. Casey fears getting in trouble; Riley insists on calling emergency services. What do you do?',answers:[['Call emergency services and follow the dispatcher’s instructions.','Help is requested. The outcome is uncertain, but the siblings stop arguing long enough to prioritize the person in danger.','repair'],['Hesitate because you are afraid of being blamed.','The delay makes a frightening situation worse. The scene ends with Riley calling for help, and the siblings face the damage that fear caused.','escalate']]}
  ])},
  {key:'drinking',minStage:3,description:'Mom’s drinking disrupts dinner and divides the siblings.',pack:episode('drinking','Dinner with the volume up','Mom has been drinking and starts an argument at dinner. Casey wants everyone to pretend it is normal. Riley wants to leave the table. What do you do?',[
    ['Leave the argument with Riley and suggest talking when Mom is sober.','Riley feels less trapped. Casey is upset that the family performance has ended, but the siblings have space to breathe.','repair'],
    ['Tell Riley to stop upsetting Mom and sit back down.','Riley feels responsible for an adult’s drinking. Casey gets a quieter table, while resentment grows underneath it.','escalate']
  ],[
    {title:'The sober conversation',question:'The next morning Mom says she barely remembers dinner. Casey asks you to drop it; Riley wants someone to acknowledge what happened. What do you do?',answers:[['Describe what happened and set a boundary about future arguments.','The problem is not instantly fixed, but Riley no longer has to defend their own memory of the night.','repair'],['Accept the apology and refuse to discuss dinner again.','The apology ends the conversation before the family agrees on what needs to change. The tension remains.','avoid']]},
    {title:'Who keeps the peace?',question:'Riley says they are tired of being blamed whenever Mom drinks. Casey insists someone has to keep the peace. What do you say?',answers:[['Admit Riley is not responsible for managing Mom’s drinking.','Casey has to reconsider what keeping the peace costs. Riley receives a clear apology instead of another instruction to behave.','repair'],['Insist Riley is too sensitive.','Riley stops trying to explain. The quiet looks like peace to Casey, but the relationship has become less safe.','escalate']]}
  ])},
  {key:'affair',minStage:3,description:'Dad’s affair with the neighbor turns you into the keeper of a secret.',pack:episode('affair','The neighbor’s porch light','Dad admits he is sleeping with the neighbor and asks you not to tell Mom. Casey wants to protect him; Riley says the secret is tearing the family apart. What do you do?',[
    ['Tell Dad you will not lie for him and urge him to speak honestly with Mom.','Riley feels supported. Casey fears what comes next, but you refuse to make the siblings responsible for Dad’s choices.','repair'],
    ['Agree to cover for Dad for now.','The secret buys a quiet evening. Riley loses trust in the family’s promises, and Casey becomes invested in keeping the story consistent.','avoid']
  ],[
    {title:'After the confession',question:'Mom knows about the affair. Your parents argue, and Casey wants the siblings to choose a side. Riley wants to stay out of their marriage. What do you say?',answers:[['We can care about both of them without becoming messengers or judges.','The siblings make room for different feelings and stop demanding a loyalty test from one another.','repair'],['Anyone who refuses to pick a side is a coward.','The parents’ conflict becomes a sibling conflict too. Riley feels that belonging now depends on agreeing with you.','escalate']]},
    {title:'A secret with witnesses',question:'Mom discovers the affair and learns that you knew. Riley says the cover-up hurt almost as much as the affair itself. What do you do?',answers:[['Admit that hiding it was wrong without taking responsibility for Dad’s affair.','An honest distinction leaves room for an apology and boundaries. Trust needs time, but the siblings can begin repairing their part.','repair'],['Say Dad made us lie, so nobody can blame us.','Dad’s pressure was real, but refusing to acknowledge the hurt leaves Riley unheard and the family divided.','avoid']]}
  ])},
  {key:'dog',minStage:1,description:'The missing dog brings out blame, cooperation, and relief.',pack:episode('dog','An empty leash','The dog has run away through an open gate. Casey blames Riley, who is already crying. What do you do?',[
    ['Stop the blame and organize a search together.','The siblings divide the search instead of turning panic into punishment. Riley has something useful to do.','repair'],
    ['Demand that Riley admit whose fault it was before helping.','Riley becomes overwhelmed. Casey feels backed up, but the family loses time arguing while the dog is still missing.','escalate']
  ],[
    {title:'A familiar bark',question:'A neighbor has found the dog safe. Casey wants to take all the credit for the search. Riley quietly hands you the leash. What do you say?',answers:[['Thank everyone and make a plan to secure the gate.','Relief becomes a shared memory. The siblings agree on a practical change instead of choosing a winner.','repair'],['Let Casey take the credit so the happy ending stays happy.','The dog is home, but Riley remembers being useful only when nobody was watching.','avoid']]},
    {title:'Home, but not over',question:'The dog returns safely with a neighbor. Riley asks why you cared more about blame than helping. Casey tells you to forget the argument. What do you do?',answers:[['Apologize to Riley and help fix the gate.','The dog’s return does not erase the argument, but taking responsibility gives Riley a reason to reconnect.','repair'],['Tell Riley the dog coming home proves there was no harm done.','The missing dog is safe. Riley is left with the message that hurt only counts when it leaves visible damage.','escalate']]}
  ])}
].map(entry=>({...entry,pack:{...entry.pack,cards:entry.pack.cards.map(card=>({...card,minStage:entry.minStage}))}}));}

function crisisEpisodes(){
  const housing=episode('housing','Nowhere to put the boxes','The family has lost its housing. Casey wants to hide it from everyone. Riley asks where you are sleeping tonight. What do you do?',[
    ['Ask a trusted person for help making a plan for tonight.','Naming the immediate need gives Riley something concrete to hold onto. Casey is embarrassed, but nobody has to pretend the boxes are a holiday.','repair'],
    ['Tell Riley everything is fine and refuse to discuss it.','The reassurance does not answer where anyone will sleep. Casey supports the silence while Riley becomes more anxious.','avoid']
  ],[
    {title:'One room, too many feelings',question:'A relative offers a temporary room. Casey resents the lack of privacy; Riley worries you will be asked to leave. What do you say?',answers:[['Agree on shared expectations and let everyone name what is hard.','The room is still crowded and housing remains uncertain. The siblings at least have a plan they helped make.','repair'],['Tell Casey to be grateful and stop complaining.','Help meets an immediate need, but shutting down Casey turns understandable frustration into resentment.','escalate']]},
    {title:'The truth in the hallway',question:'Riley overhears the adults discussing temporary accommodation and asks why you lied. Casey says you were protecting them. What do you do?',answers:[['Apologize and explain what is known and what is still uncertain.','Riley gets an honest answer without being asked to solve the adults’ problems. The siblings can begin trusting each other again.','repair'],['Say Riley should not have been listening.','The housing problem remains, and Riley learns that asking for reassurance can become another accusation.','escalate']]}
  ]);
  const job=episode('job-loss','The last paycheck','Dad loses his job. Bills are piling up, and he snaps when Riley asks about dinner. Casey insists nobody should mention money. What do you do?',[
    ['Help the family discuss immediate needs without blaming each other.','The conversation is uncomfortable, but Riley is no longer treated as the problem for asking a basic question.','repair'],
    ['Join Casey in pretending nothing has changed.','Silence delays a difficult conversation. Riley still notices the unopened bills and feels alone with the worry.','avoid']
  ],[
    {title:'What the paycheck covered',question:'The family reviews its bills and discovers a serious rent shortfall. Casey wants to promise Riley it is handled; Riley asks for the truth. What do you say?',answers:[['Explain that help is being sought, but housing is at risk.','The siblings stop promising an outcome they cannot guarantee. The story continues into the family’s housing crisis.','repair'],['Promise the rent is covered even though it is not.','The promise buys a quiet evening and a bigger breach of trust when the family has to leave.','avoid']]},
    {title:'The notice on the table',question:'After weeks of missed payments, the adults say the family must leave its home. Casey wants someone to blame. Riley starts packing the dog’s things. What do you do?',answers:[['Focus on where everyone can stay and what they need tonight.','The siblings redirect panic into immediate needs. The next chapter begins with the family looking for shelter.','repair'],['Blame Dad in front of everyone.','Anger finds a target without creating a place to stay. The family carries that argument into its next chapter.','escalate']]}
  ]);
  for(const card of job.cards.slice(1))for(const answer of card.choices)answer.nextId=housing.rootId;
  job.cards.push(...housing.cards);
  return [
    {key:'cult',minStage:3,description:'A controlling group asks the family to cut off outsiders.',pack:episode('cult','The only people who understand','Casey joins a group that calls itself a new family. Its leader wants money and says concerned relatives are enemies. Riley asks whether Casey is being manipulated. What do you do?',[
      ['Keep contact with Casey and ask about the pressure without insulting them.','Casey remains defensive, but Riley sees a way to express concern without making love conditional.','repair'],
      ['Join Casey and agree to cut off anyone who questions the leader.','The group gains influence as the siblings grow apart. Riley feels shut out for asking a reasonable question.','escalate']
    ],[
      {title:'A door left open',question:'Casey privately admits the group makes leaving feel like betrayal. Riley wants to say “I told you so.” How do you respond?',answers:[['Offer support and space to decide without demanding an apology first.','Casey has someone to contact outside the group. Leaving may take time, but the siblings rebuild a connection.','repair'],['Demand Casey admit they were foolish before you help.','Shame makes Casey less willing to talk. Riley hears another version of support with conditions attached.','escalate']]},
      {title:'The loyalty test',question:'The leader tells you to ignore Riley’s calls to prove your loyalty. Casey hesitates. What do you do?',answers:[['Answer Riley and refuse the demand to isolate yourselves.','The siblings reopen contact and question why belonging requires cutting people off.','repair'],['Block Riley and pressure Casey to do the same.','The group’s approval comes at the cost of a family connection. Riley is left outside another closed door.','escalate']]}
    ])},
    {key:'dss',minStage:1,description:'A report brings a child-welfare worker to the family home.',pack:episode('dss','A knock from DSS','A child-welfare worker visits after a report about safety at home. Casey wants everyone to rehearse the same story. Riley is frightened. What do you do?',[
      ['Encourage everyone to describe what they actually experienced.','Riley feels less pressure to protect appearances. The visit begins with individual experiences instead of a rehearsed family script.','repair'],
      ['Pressure Riley to repeat Casey’s version.','Riley feels caught between safety and loyalty. The siblings’ trust suffers before the conversation even begins.','escalate']
    ],[
      {title:'After the visit',question:'The visit ends with further conversations planned, not an immediate resolution. Casey blames whoever made the report. Riley wants to know what happens next. What do you say?',answers:[['Focus on the stated next steps and the safety concerns that need attention.','Nobody can promise the outcome, but Riley gets an honest explanation and the siblings stop turning uncertainty into a blame hunt.','repair'],['Promise nothing will happen and insist everyone forget it.','The promise cannot settle an ongoing process. Riley is left confused when another conversation is scheduled.','avoid']]},
      {title:'Whose version counts?',question:'Riley says the rehearsed account left out something important. Casey calls that disloyal. How do you respond?',answers:[['Say Riley deserves to speak honestly without punishment from the siblings.','Riley regains some room to describe their experience. The family still has concerns to address, but honesty is no longer treated as betrayal.','repair'],['Tell Riley family business must stay inside the family.','The demand protects appearances at the cost of Riley’s trust. The underlying safety concerns remain unresolved.','escalate']]}
    ])},
    {key:'car',minStage:1,description:'A breakdown turns a normal trip into a family argument.',pack:episode('car','Steam on the roadside','The car breaks down during a family trip. Everyone is stuck waiting in a safe place for assistance. Casey blames Dad’s maintenance; Riley is worried about getting home. What do you do?',[
      ['Check what everyone needs while the adults arrange help.','Riley feels noticed. Casey still complains, but the siblings turn some of their energy toward helping one another.','repair'],
      ['Join the argument about whose fault it is.','The car stays broken while the family gets louder. Riley has nobody calmly explaining the wait.','escalate']
    ],[
      {title:'The repair estimate',question:'The repair is expensive. Casey wants to joke about Dad being useless, while Riley asks if you can still visit Grandma. What do you say?',answers:[['Help discuss alternative transport without making Dad the punchline.','The family considers a different plan. Riley gets an answer, and Casey has less incentive to turn worry into ridicule.','repair'],['Tell Riley the visit obviously does not matter now.','Money worries become a reason to dismiss Riley’s feelings. The practical problem and the hurt both remain.','escalate']]},
      {title:'The ride home',question:'A friend gives the family a ride. Casey is still angry, and Riley is embarrassed by the argument. What do you do?',answers:[['Thank the friend and apologize for adding to the fight.','The breakdown is not magically solved, but the siblings stop carrying the roadside argument into every conversation.','repair'],['Keep explaining why Dad deserved the criticism.','The ride is quieter only because Riley stops responding. The family reaches home with the same resentment.','avoid']]}
    ])},
    {key:'job-loss',minStage:1,description:'Dad loses his job; the story continues into a housing crisis. Six scenes.',pack:job},
    {key:'housing',minStage:1,description:'A family without stable housing looks for help and a place to stay.',pack:housing}
  ];
}

function turningPointEpisodes(){return [
  {key:'family-violence',minStage:3,description:'A dark, non-graphic story about choosing violence or stepping back before irreversible loss.',pack:episode('family-violence','An irreversible decision','In this dark story, you decide you want to kill your family after a bitter argument. There is still time to step away before anyone is hurt. What do you choose?',[
    ['Leave the confrontation and contact someone who can help keep everyone safe.','You create distance instead of turning a thought into an irreversible act. The argument remains unresolved, but everyone survives this moment.','repair'],
    ['Hold onto the decision and refuse to step away.','The story reaches a final crossroads. Your anger does not erase the lives or choices of the people around you.','escalate']
  ],[
    {title:'The morning that still exists',question:'The family is alive, but frightened by what you said. Casey wants an immediate promise that everything is fine. Riley wants distance. How do you respond?',answers:[['Respect their distance and accept help without demanding forgiveness.','Safety and trust will take more than an apology. The story ends with you accepting responsibility and the family having room to decide what contact feels safe.','repair'],['Demand that everyone forget it because nothing happened.','The demand deepens the fear. The family keeps its distance, and the story ends with trust unresolved rather than restored.','escalate']]},
    {title:'The last chance to leave',question:'This story has reached a choice that cannot be repaired afterward. Do you step away, or carry out the violence?',answers:[['Step away and call for immediate help.','Nobody is killed. The story ends with outside help being sought and the family separated for safety; reconciliation is not promised.','repair'],['Carry out the killings. End this story with irreversible loss.','The story cuts to black. Your family is dead. There is no reward, reconciliation, or next chapter in this episode—only lives lost and the consequences of your choice.','escalate']]}
  ])},
  {key:'dealing',minStage:3,description:'Drug dealing strains trust and brings consequences without instructions for committing it.',pack:episode('dealing','Money nobody asks about','You have started selling drugs. Casey likes the extra money, while Riley asks why people keep arriving at strange hours. What do you tell them?',[
    ['Admit what is happening and say you want to stop involving the household.','Riley finally gets an honest answer. Casey resents losing the money, but the siblings can discuss the risk without pretending it is harmless.','repair'],
    ['Tell Riley the money is all they need to know about.','The secrecy makes Riley feel unsafe at home. Casey backs you up, and the siblings split over what they are willing to ignore.','escalate']
  ],[
    {title:'An expensive change of direction',question:'You have stopped dealing, but the income is gone and Casey calls you unreliable. Riley wants a home that does not revolve around secrecy. What do you say?',answers:[['Acknowledge the money problem while keeping the boundary about stopping.','The bills remain real. The siblings start discussing ordinary work and help instead of asking Riley to trade peace for money.','repair'],['Blame Riley for making you give it up.','You shift the cost of your decision onto the sibling who raised a concern. The dealing has stopped, but the resentment has not.','escalate']]},
    {title:'When the secret reaches home',question:'After a frightening incident connected to the dealing, Riley refuses to stay around it. Casey asks you to insist that nothing is wrong. What do you choose?',answers:[['Stop defending the secret and support Riley finding a safer place to stay.','Riley is allowed to set a boundary. The story ends with consequences still unresolved, but without demanding loyalty at any cost.','repair'],['Accuse Riley of abandoning the family.','Riley leaves the conversation. The money has become another reason the family expects silence instead of trust.','escalate']]}
  ])},
  {key:'voices',minStage:3,description:'A character living with schizophrenia experiences voices and navigates privacy, support, and misunderstanding.',pack:episode('voices','More than one conversation','In this episode, you are living with schizophrenia. During an ordinary family breakfast, a voice you hear says, “They are talking about you.” Riley is actually asking whether you want toast. What do you do?',[
    ['Say that you are having a difficult morning and ask Riley to repeat the question.','Riley slows down and gives you time. The voice does not disappear, but you get to answer the real conversation without pretending the experience is easy.','repair'],
    ['Leave without explaining because the overlapping conversations feel exhausting.','You find some quiet. Riley is unsure what happened, and Casey starts filling the silence with assumptions you did not choose.','avoid']
  ],[
    {title:'Help without taking over',question:'You explain that hearing voices can be difficult. Casey offers to speak for you at every appointment, while Riley asks what kind of company you actually want. How do you respond?',answers:[['Tell them what support you want and which conversations you want to handle yourself.','Casey has a chance to help without taking control. Riley hears that support can include respecting privacy and independence.','repair'],['Let Casey make the decisions because challenging them feels too tiring today.','The pressure eases for the moment, but your own preferences remain unspoken. The story leaves room to revisit them later.','avoid']]},
    {title:'A person beyond the diagnosis',question:'Casey starts explaining all your opinions as symptoms. Riley says you are still allowed to disagree with the family. What do you say?',answers:[['Explain that the diagnosis does not erase my preferences or my right to be heard.','Riley backs your boundary. Casey has to consider you as a whole person instead of treating a label as the answer to every disagreement.','repair'],['Withdraw from the discussion and keep my preferences to myself.','You protect your energy for now. The story ends with the family still needing to learn how to listen without reducing you to a diagnosis.','avoid']]}
  ])},
  {key:'school-fight',minStage:2,description:'A school conflict becomes a fight or a difficult decision to walk away.',pack:episode('school-fight','After the last bell','At school, another student insults Riley and shoves you. Casey says you will look weak if you leave. What do you do?',[
    ['Move away with Riley and get a staff member involved.','Riley gets out of the confrontation. Casey questions the choice, but you have not let the insult decide what happens next.','repair'],
    ['Fight the student.','The fight is broken up. Riley is frightened, and the school calls home; Casey’s encouragement does not protect you from the aftermath.','escalate']
  ],[
    {title:'The version everyone repeats',question:'Casey says you ran away. Riley knows you helped them leave safely. What do you say at home?',answers:[['Explain what happened without asking Riley to prove my toughness.','The siblings disagree about pride, but Riley is not forced to repay help with a performance of loyalty.','repair'],['Blame Riley for putting me in that position.','The confrontation is over, but Riley now feels responsible for the insult and the family argument.','escalate']]},
    {title:'The meeting at school',question:'At a school meeting about the fight, Casey wants you to leave out your own actions. Riley asks whether you regret what happened. What do you say?',answers:[['Describe the whole incident, including what I did and what happened to Riley.','The school still decides its response. The siblings hear an honest account instead of another family story that requires everyone to lie.','repair'],['Say I would do it again and dismiss Riley’s fear.','The fight becomes a point of pride while Riley’s experience disappears from the conversation. The story ends with trust damaged.','escalate']]}
  ])},
  {key:'pregnancy',minStage:3,description:'An adult partner’s pregnancy and abortion bring questions of autonomy, feelings, and privacy.',pack:episode('pregnancy','Two lines, different feelings','In this adult episode, your girlfriend tells you that she is pregnant and you are the other parent. She says she has decided to have an abortion. You have complicated feelings. What do you say?',[
    ['Listen, respect her decision, and ask what support she wants.','She does not have to defend ownership of her decision. You make room for your feelings without turning them into pressure on her.','repair'],
    ['Insist she change her decision because of how I feel.','She sets a firm boundary. The disagreement becomes about whether her choice will be respected, and trust suffers.','escalate']
  ],[
    {title:'After the appointment',question:'She has had the abortion and asks for privacy. Casey wants details; Riley says it is not a family vote. What do you do?',answers:[['Protect her privacy and talk about my own feelings without disclosing hers.','The siblings learn that caring does not create a right to someone else’s private experience. You leave room for different feelings without assigning blame.','repair'],['Share the details because the family keeps asking.','She learns that a private experience became household conversation. The story ends with an apology still owed and trust to rebuild.','escalate']]},
    {title:'A boundary after the decision',question:'She has had the abortion and says your pressure hurt her. Casey tells you to make her feel guilty; Riley asks whether you can acknowledge the harm. What do you do?',answers:[['Apologize for the pressure without expecting forgiveness or continued dating.','The apology does not decide the future of the relationship. It does give the family an example of respecting a decision that was never theirs to make.','repair'],['Keep insisting that my feelings should have settled the decision.','She ends the conversation. The story closes on a boundary, not an argument you can win by wearing her down.','escalate']]}
  ])},
  {key:'transition',minStage:3,description:'A transgender character chooses how to share their identity and set boundaries with family.',pack:episode('transition','The name I want you to use','You have come to understand that you are transgender and decide to tell your siblings. You want to begin using a name and pronouns that fit you. Casey worries about other people’s reactions; Riley asks what you need. What do you choose?',[
    ['Tell them what name and pronouns I want used and who may be told.','Riley listens. Casey has questions, but your identity and privacy are stated clearly instead of left for the family to decide.','repair'],
    ['Tell Riley privately and ask for time before sharing more widely.','Riley agrees to keep the conversation private. You choose your own pace, while some family conversations remain for another day.','avoid']
  ],[
    {title:'A correction at dinner',question:'Casey uses the old name and says you are making dinner awkward. Riley offers a simple correction. How do you respond?',answers:[['Restate the name I use and ask Casey to make the effort.','Riley supports the boundary. Casey has an opportunity to change their behavior; respect is not something you have to earn by staying silent.','repair'],['Leave the dinner conversation for now.','You take space from a hurtful exchange. The story ends with your boundary still valid and the family’s work unfinished.','avoid']]},
    {title:'Who gets to tell my story?',question:'Casey finds out you told Riley first and feels excluded. Riley has kept your confidence. What do you say?',answers:[['Explain that sharing my identity is my decision, not a sibling competition.','Casey has to separate feeling left out from being entitled to private information. Riley is not punished for respecting your trust.','repair'],['Let the subject drop because I am not ready for this conversation.','You keep control of what you disclose today. The story leaves space for a later conversation without treating transition as a family vote.','avoid']]}
  ])},
  {key:'restored-car',minStage:3,description:'You buy and restore a car, then confront the aftermath when Mom crashes it while drunk.',pack:episode('restored-car','Finally running','You buy an old car and spend months fixing it. It finally runs. Mom wants to borrow it for a night out, and Casey says refusing would be selfish. What do you do?',[
    ['Explain that permission comes with clear expectations about driving sober.','Riley supports the boundary. Casey grumbles, but the car is recognized as something you worked for rather than family property by default.','repair'],
    ['Hand over the keys to avoid another argument.','The argument stops, but expectations remain unclear. Riley notices how easily your work became something you had to surrender to keep the peace.','avoid']
  ],[
    {title:'The call about the car',question:'Mom drove after drinking and crashed your restored car. Nobody was physically hurt, but the car is badly damaged. Casey asks you to forgive her immediately. What do you say?',answers:[['Say I am relieved everyone survived, but the damage and drinking still need accountability.','Relief does not erase the loss. Riley hears that compassion and boundaries can exist in the same sentence.','repair'],['Tell Casey they must choose between me and Mom.','The wreck becomes a sibling loyalty test. Your anger is understandable, but the demand gives the family another conflict without repairing the car.','escalate']]},
    {title:'The work she wrecked',question:'Mom crashes the car after drinking. Everyone survives, but months of your work are gone. Riley asks what you need; Casey says “it is only a car.” What do you do?',answers:[['Explain what the work meant and refuse to minimize the dangerous choice she made.','Riley listens to the loss beneath the repair bill. Casey is asked to acknowledge harm instead of deciding how quickly you should get over it.','repair'],['Pretend it does not matter so nobody has to discuss it.','The car remains damaged. Your silence protects the evening while leaving the loss and Mom’s behavior unresolved.','avoid']]}
  ])},
  {key:'dui',minStage:3,description:'A choice about driving after drinking leads to a safe ride or a DUI aftermath.',pack:episode('dui','The keys at closing time','You have been drinking and are about to leave. Casey says the drive is short; Riley offers to help arrange a sober ride. What do you choose?',[
    ['Leave the car and accept a sober ride.','You get home without driving. Casey’s teasing fades, while Riley knows their concern was heard.','repair'],
    ['Drive after drinking.','The episode cuts to a traffic stop and a DUI charge. Nobody is shown hurt, but your choice has consequences that the family cannot joke away.','escalate']
  ],[
    {title:'Picking up the car',question:'The next day you need help collecting the car. Casey complains about the inconvenience. Riley says inconvenience was the better outcome. What do you say?',answers:[['Thank Riley and make a plan for future nights out before drinking.','The siblings turn the awkward errand into a practical agreement instead of a competition about who can take more risks.','repair'],['Say next time I will drive so nobody can complain.','The family hears a warning that embarrassment might shape your next decision. Riley feels that their help has been treated as an insult.','escalate']]},
    {title:'A ride you cannot demand',question:'While dealing with the DUI case, you need transport and support. Casey wants you to call it bad luck. Riley wants you to take responsibility. What do you say?',answers:[['Own the decision and ask for help without treating anyone as my unpaid driver.','The case remains unresolved. Riley can choose what help to offer, and Casey hears accountability without a promise that one apology fixes everything.','repair'],['Blame everyone who failed to stop me.','The family cannot undo your choice. Blaming them turns a request for help into another reason to keep their distance.','escalate']]}
  ])}
];}
